---
title: "Untitled"
output: html_document
date: "2024-04-11"
---
```{r}
data1 = temp_fragment_data7(mu = 0, r = 2, sigma = 1, n = 140, m =20, sigma_epsilon = 0.01, domain = c(0, 1), delta = 0.5)
data2 = temp_fragment_data9(mu = 0, r = 2, sigma = 1, n = 100, m = 20, sigma_epsilon = 0.01, domain = c(0, 1), delta = 0.5)
data3 = temp_fragment_data10(mu = 0, r = 2, sigma = 1, n = 120, m = 20, sigma_epsilon = 0.01, domain = c(0, 1), delta = 0.5)
data = list("t"= rbind(data1$t, data2$t, data3$t), "y" = rbind(data1$y, data2$y, data3$y), "r" = cbind(data1$r, data2$r, data3$r))
```

```{r}
lambda = 0.00001
ext = 0.1
maxIt = 1
```


```{r}
cov.obj_whole.1 <- cov_basis(data$t[1:240,], data$y[1:240,], data$r[,1:4800], r=2, lambda, ext, maxIt)
cov.obj_whole.2 <- cov_basis(data$t[141:360,], data$y[141:360,], data$r[,2801:7200], r=2, lambda, ext, maxIt)

cov.obj_first <- cov_basis(data$t[1:140,], data$y[1:140,], data$r[,1:2800], r=2, lambda, ext, maxIt)
cov.obj_second <- cov_basis(data$t[141:240,], data$y[141:240,], data$r[, 2801:4800], r=2, lambda, ext, maxIt)
cov.obj_third <- cov_basis(data$t[241:360,], data$y[241:360,], data$r[, 4801:7200], r=2, lambda, ext, maxIt)

cov.obj_whole.1$error - cov.obj_first$error - cov.obj_second$error 
cov.obj_whole.2$error - cov.obj_second$error - cov.obj_third$error
```


```{r}
# xi_set = c(200,300)
# xi_set = c(350, 400, 500, 600, 700, 800)
xi_set = c(250, 300, 400, 500, 600)
CV_cpt_result = CV_search_DP_fragment(data$t, data$y, data$r, r = 2, lambda, xi_set, ext, maxIt)
min_idx = which.min(CV_cpt_result$test_error) 
xi_set[min_idx]
cpt_init = unlist(CV_cpt_result$cpt_hat[min_idx])
cpt_init
```


```{r}
data1 = temp_fragment_data13(mu = 0, r = 2, sigma = 1, n = 140, m =20, sigma_epsilon = 0.01, domain = c(0, 1), delta = 0.6)
data2 = temp_fragment_data14(mu = 0, r = 2, sigma = 1, n = 100, m = 20, sigma_epsilon = 0.01, domain = c(0, 1), delta = 0.6)
data3 = temp_fragment_data15(mu = 0, r = 2, sigma = 1, n = 120, m = 20, sigma_epsilon = 0.01, domain = c(0, 1), delta = 0.6)
data = list("t"= rbind(data1$t, data2$t, data3$t), "y" = rbind(data1$y, data2$y, data3$y), "r" = cbind(data1$r, data2$r, data3$r))
```

```{r}
lambda = 0.00001
ext = 0.1
maxIt = 1
```

```{r}
# xi_set = c(200,300)
# xi_set = c(350, 400, 500, 600, 700, 800)
# xi_set = c(400, 450, 500, 600)
xi_set = c(550, 600,700, 800, 900)
# xi_set = c(300, 350, 400, 450)
CV_cpt_result = CV_search_DP_fragment(data$t, data$y, data$r, r = 2, lambda, xi_set, ext, maxIt)
min_idx = which.min(CV_cpt_result$test_error) 
xi_set[min_idx]
cpt_init = unlist(CV_cpt_result$cpt_hat[min_idx])
cpt_init
```



