# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expM <- function(X, S) {
    .Call(`_FragmentCP_expM`, X, S)
}

RgradQ <- function(Lt, Lr, L, B, U, V, W, lam, weight) {
    .Call(`_FragmentCP_RgradQ`, Lt, Lr, L, B, U, V, W, lam, weight)
}

RhessianQ <- function(Lt, Lr, S, B, U, V, W, lam, weight, X) {
    .Call(`_FragmentCP_RhessianQ`, Lt, Lr, S, B, U, V, W, lam, weight, X)
}

deriv_fourier <- function(K, domain, grid, order) {
    .Call(`_FragmentCP_deriv_fourier`, K, domain, grid, order)
}

evaluate_basis <- function(K, domain, grid) {
    .Call(`_FragmentCP_evaluate_basis`, K, domain, grid)
}

auxiliary_mat <- function(r, Lt) {
    .Call(`_FragmentCP_auxiliary_mat`, r, Lt)
}

minimizeQ <- function(Lt, Lr, auxmat, lambda, weight, L0, maxIt) {
    .Call(`_FragmentCP_minimizeQ`, Lt, Lr, auxmat, lambda, weight, L0, maxIt)
}

minimizeL <- function(Lt, Lr, auxmat, lambda, weight) {
    .Call(`_FragmentCP_minimizeL`, Lt, Lr, auxmat, lambda, weight)
}

C_hat <- function(Lt, Lr, auxmat, lambda, weight, maxIt) {
    .Call(`_FragmentCP_C_hat`, Lt, Lr, auxmat, lambda, weight, maxIt)
}

cov_basis <- function(Lt, Ly, Lr, r, lambda, ext, maxIt) {
    .Call(`_FragmentCP_cov_basis`, Lt, Ly, Lr, r, lambda, ext, maxIt)
}

error_seg_fragment <- function(Lt, Ly, Lr, r, s, e, lambda, ext, maxIt) {
    .Call(`_FragmentCP_error_seg_fragment`, Lt, Ly, Lr, r, s, e, lambda, ext, maxIt)
}

DP_fragment <- function(Lt, Ly, Lr, r, lambda, xi, ext, maxIt, Delta) {
    .Call(`_FragmentCP_DP_fragment`, Lt, Ly, Lr, r, lambda, xi, ext, maxIt, Delta)
}

